"""Deleted Wantbeta; Added EmailList, Added relation meeting_emails

Revision ID: 2922166de611
Revises: 43ac0c4fc0e6
Create Date: 2017-10-31 17:20:26.928010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2922166de611'
down_revision = '43ac0c4fc0e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_email'), 'email', ['email'], unique=True)
    op.create_table('meeting_emails',
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], )
    )
    op.drop_table('wantbeta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wantbeta',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation=u'utf8_bin', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_bin',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('meeting_emails')
    op.drop_index(op.f('ix_email_email'), table_name='email')
    op.drop_table('email')
    # ### end Alembic commands ###
