"""Deleted demo table

Revision ID: 43ac0c4fc0e6
Revises: 39f55a466c43
Create Date: 2017-10-27 16:44:30.590802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43ac0c4fc0e6'
down_revision = '39f55a466c43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'meeting_ibfk_2', 'meeting', type_='foreignkey')
    op.drop_column('meeting', 'demo_email')
    op.drop_constraint(u'muddy_ibfk_1', 'muddy', type_='foreignkey')
    op.drop_column('muddy', 'demo_email')
    op.drop_table('demo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('muddy', sa.Column('demo_email', mysql.VARCHAR(collation=u'utf8_bin', length=100), nullable=False))
    op.create_foreign_key(u'muddy_ibfk_1', 'muddy', 'demo', ['demo_email'], ['email'], ondelete=u'CASCADE')
    op.add_column('meeting', sa.Column('demo_email', mysql.VARCHAR(collation=u'utf8_bin', length=100), nullable=False))
    op.create_foreign_key(u'meeting_ibfk_2', 'meeting', 'demo', ['demo_email'], ['email'], ondelete=u'CASCADE')
    op.create_table('demo',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation=u'utf8_bin', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_bin',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
