"""empty message

Revision ID: e78b7fccd7e8
Revises: 
Create Date: 2017-09-05 15:53:53.189009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e78b7fccd7e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('roles_users')
    op.drop_table('course')
    op.drop_table('demo')
    op.drop_table('meeting')
    op.drop_table('muddy')
    op.drop_table('role')
    op.drop_table('migrate_version')
    op.drop_table('wantbeta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wantbeta',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation=u'utf8_bin', length=100), index=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_bin',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('migrate_version',
    sa.Column('repository_id', mysql.VARCHAR(collation=u'utf8_bin', length=250), nullable=False),
    sa.Column('repository_path', mysql.TEXT(collation=u'utf8_bin'), nullable=True),
    sa.Column('version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('repository_id'),
    mysql_collate=u'utf8_bin',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('role',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation=u'utf8_bin', length=80), nullable=True),
    sa.Column('description', mysql.VARCHAR(collation=u'utf8_bin', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_bin',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('muddy',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('body', mysql.VARCHAR(collation=u'utf8_bin', length=700), nullable=True),
    sa.Column('like_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('meeting_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('demo_email', mysql.VARCHAR(collation=u'utf8_bin', length=100), nullable=False),
    sa.ForeignKeyConstraint(['demo_email'], [u'demo.email'], name=u'muddy_ibfk_3', ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], [u'meeting.id'], name=u'muddy_ibfk_1', ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'muddy_ibfk_2', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_bin',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('meeting',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('demo_email', mysql.VARCHAR(collation=u'utf8_bin', length=100), nullable=False),
    sa.Column('title', mysql.VARCHAR(collation=u'utf8_bin', length=100), nullable=True),
    sa.Column('type_meeting', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('close_stat', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('close_opt', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('url_string', mysql.VARCHAR(collation=u'utf8_bin', length=80), nullable=True),
    sa.Column('prompt', mysql.VARCHAR(collation=u'utf8_bin', length=300), nullable=True),
    sa.Column('live_till', mysql.DATETIME(), nullable=True),
    sa.Column('live_till_hours', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('note', mysql.VARCHAR(collation=u'utf8_bin', length=500), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], [u'course.id'], name=u'meeting_ibfk_1', ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['demo_email'], [u'demo.email'], name=u'meeting_ibfk_3', ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'meeting_ibfk_2', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_bin',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('demo',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation=u'utf8_bin', length=100), nullable=False, index=True, unique=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_bin',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('course',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(collation=u'utf8_bin', length=100), nullable=True),
    sa.Column('type_course', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('level', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sbj1', mysql.VARCHAR(collation=u'utf8_bin', length=100), nullable=True),
    sa.Column('sbj2', mysql.VARCHAR(collation=u'utf8_bin', length=100), nullable=True),
    sa.Column('sbj3', mysql.VARCHAR(collation=u'utf8_bin', length=100), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('live_stat', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('note', mysql.VARCHAR(collation=u'utf8_bin', length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'course_ibfk_1', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_bin',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('roles_users',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], [u'role.id'], name=u'roles_users_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'roles_users_ibfk_1'),
    mysql_collate=u'utf8_bin',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('social_nw', mysql.VARCHAR(collation=u'utf8_bin', length=64), nullable=True),
    sa.Column('nickname', mysql.VARCHAR(collation=u'utf8_bin', length=64), nullable=True, index=True, unique=True),
    sa.Column('email', mysql.VARCHAR(collation=u'utf8_bin', length=100), nullable=True, index=True, unique=True),
    sa.Column('password', mysql.VARCHAR(collation=u'utf8_bin', length=255), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('last_seen', mysql.DATETIME(), nullable=True),
    sa.Column('affiliation', mysql.VARCHAR(collation=u'utf8_bin', length=100), nullable=True),
    sa.Column('confirmed_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_bin',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
